### ISSUE TITLE
After merged 0.18.0 and run 'yarn dev'，the app not start. 

### ISSUE THREAD

**Issue by nEdAy** [electron-react-boilerplate/electron-react-boilerplate#2327]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
Step 1: 0.17.x is ok, merged 0.18.0

Step 2: 
rm -rf node_modules &&
yarn cache clean &&
yarn &&
yarn electron-rebuild &&
yarn dev

Step 3: 
expect app start.

## Current Behavior

windows 10

but nothing happend.

run 'yarn package' is ok. 

λ yarn dev

`yarn run v1.19.1
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...

> electron-react-boilerplate@0.18.0 start-main-dev D:\WorkSpace\HCCN_Projects\sapp-deployment-tools
> cross-env HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js

 libpng warning: iCCP: cHRM chunk does not match sRGB`

## Your Environment

- Node version : v10.16.3
- Version or Branch used : master
- Operating System and version : Windows 10 1909   18963.476
- Link to your project : master, no code change

**Comment by nEdAy** [comment]
yarn 1.19.1

**Comment by nEdAy** [comment]
electron-builder  version=22.1.0 os=10.0.18363

**Comment by clementAC** [comment]
Be careful with this new version, there is a rollback with the two package.json structure. 
If you have native libs that need to be recompiled you have to declare them in the app/package.json. 
check this documentation : https://www.electron.build/tutorials/two-package-structure

**Comment by nEdAy** [comment]
But why can't start the app using only the template?
I have n’t changed anything, just do 

> rm -rf node_modules &&
> yarn cache clean &&
> yarn &&
> yarn electron-rebuild &&
> yarn dev

But after that, nothing happened and the app didn't open automatically.

**Comment by nEdAy** [comment]
I tested tag v0.17.1 and can open the app normally after the above steps

**Comment by nEdAy** [comment]
with 'v0.18.0' npm run 'start' is ok.

**Comment by amilajack** [comment]
I can't reproduce this on windows latest master, fresh clone, cleared cache.

**Comment by nEdAy** [comment]
ok, please wait for me to try again.

**Comment by nEdAy** [comment]
rm -rf node_modules &&
yarn cache clean &&
yarn &&
yarn electron-rebuild &&
yarn dev

nothing happened，app not open auto.

**Comment by diddiman** [comment]
It's not working for me either. I also made sure to clear my electron cache in "C:\Users\{user}\AppData\Roaming", cleared everything that was electron related (since i've previously had problems with it). Then i cloned, ran yarn and then yarn dev, nothing comes up.

**Comment by nEdAy** [comment]
yes, I also cleaned C: \ Users \ {user} \ AppData \ Roaming.

**Comment by amilajack** [comment]
Try [updating the devtools](https://electron-react-boilerplate.js.org/docs/dev-tools/#devtools-extension).

**Comment by nEdAy** [comment]
> λ set UPGRADE_EXTENSIONS=1 && yarn run dev
> yarn run v1.19.2
> $ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
> $ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
> Starting Main Process...
> 
> > sapp-deployment-tools@0.18.0 start-main-dev D:\WorkSpace\HCCN_Projects\sapp-deployment-tools
> > cross-env START_HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js
> 
> 
>  libpng warning: iCCP: cHRM chunk does not match sRGB
>

**Comment by PR0F1L3R1** [comment]
have this problem too

**Comment by ispita** [comment]
I am having the same issues, I cleared my cache in roaming, cloned the repo into a new project, ran yarn dev and only a white screen will show. Yarn start is working however.

**Comment by nEdAy** [comment]
I don't even see the white form.
This issue has troubled my development.

**Comment by amilajack** [comment]
Can you try building with `DEBUG_PROD` and see if there are any console issues in prod

**Comment by Crazycheng** [comment]
I have the same issue. I init a new project by clone this repo and run `yarn`. When I use `yarn dev`, this is my error.
![image](https://user-images.githubusercontent.com/10370599/70313232-2e369200-1850-11ea-84e5-232ac786c0ea.png)

**Comment by Crazycheng** [comment]
# environment
node: v10.15.0
Using an up-to-date master branch
Using yarn

**Comment by AntonGarasko** [comment]
1. yarn
2. yarn build
3. yarn dev
and everything will work

**Comment by diddiman** [comment]
> 
> 
>     1. yarn
> 
>     2. yarn build
> 
>     3. yarn dev
>        and everything will work

Just tried, it's not working :/

**Comment by Crazycheng** [comment]
> 1. yarn
> 2. yarn build
> 3. yarn dev 
and everything will work

I tried these commend. My app is starting without a blank. But When I change the code, the GUI will not change.

**Comment by sleeperninja** [comment]
> 1. yarn
> 2. yarn build
> 3. yarn dev
>    and everything will work

I was hopeful, but I don't even get an app window with a white app frame.

**Comment by comcaptain** [comment]
![image](https://user-images.githubusercontent.com/2543707/70369469-06e9ce80-18fd-11ea-94c6-ef419db94f6c.png)

Same for me, it doesn't work. I'll try an older version

**Comment by muhzi4u** [comment]
I am getting the same issue
<img width="1440" alt="Screenshot 2019-12-07 at 12 26 17 PM" src="https://user-images.githubusercontent.com/12408980/70370389-d00bbc80-18ec-11ea-8164-fdec2a012a29.png">

**Comment by muhzi4u** [comment]
I solved the issue by running the following command.
`UPGRADE_EXTENSIONS=1 yarn run dev`

**Comment by diddiman** [comment]
Upgrade extensions is not working either. I'm not even getting a blank page, so that might be why the upgrade extensions is not working

**Comment by nEdAy** [comment]
My OS is Windows 10. I'm not even getting a blank page.
run 'set UPGRADE_EXTENSIONS=1 && yarn run dev', not working

**Comment by spd789562** [comment]
Try #2341 possible solution. It's helped me work correctly.

**Comment by jakeols** [comment]
> Try #2341 possible solution. It's helped me work correctly.

This worked for me. Running `yarn build` like @AntonGarasko recommended helped, but live-reloading didn't work still and was fixed by #2341 for me.

**Comment by diddiman** [comment]
> Try #2341 possible solution. It's helped me work correctly.

Hmm, still can't even get the blank electron app, sounds like this could solve possible issues when the blank pages is appearing though

**Comment by hwshim0810** [comment]
There was no problem at all in Ubuntu. but have this problem in Windows10.

I tried all of the answers above but it didn't work. 

and this worked for me. (Windows 10)
```js
// main.dev.js

// Remove the bottom two blocks
if (
  process.env.NODE_ENV === 'development' ||
  process.env.DEBUG_PROD === 'true'
) {
  require('electron-debug')();
}

if (
  process.env.NODE_ENV === 'development' ||
  process.env.DEBUG_PROD === 'true'
) {
  await installExtensions();
}
```

**Comment by ThoughtZer** [comment]
> 1. yarn
> 2. yarn build
> 3. yarn dev
>    and everything will work

this worked for me. (Mac OS)

**Comment by Haradrim** [comment]
Same issue here on Windows 10 on a fresh clone, tried all the suggested solutions non of them working.
When I run _yarn dev_ the window doesn't even open.

**Comment by andywampir** [comment]
Same issue occured on Windows 10, but not on Windows 7.
I'd tested single repo for them.

**Comment by andywampir** [comment]
@comcaptain @Crazycheng
Probably i know why you got these errors in console.
In the `.html` file of your window, change these entries `process.env.HOT` onto `process.env.START_HOT`.
It works for me.

**Comment by amilajack** [comment]
`0.18.1` might resolve this issue. Please try running the latest master to test `0.18.1`

**Comment by nEdAy** [comment]
0.frech code to v0.18.1
1.cleaned C: \ Users \ {user} \ AppData \ Roaming.
2.rm -rf node_modules && yarn cache clean && yarn && yarn electron-rebuild && yarn dev

show error:

Electron failed to install correctly, please delete node_modules/electron and try installing again

**Comment by amilajack** [comment]
This is an issue on electron's side. This project does not handle electron installation.

**Comment by Geddo** [comment]
I'm on Win10 I tried evertyhing above but nothing worked. The app is not starting with yarn dev and hangs on this command:
```
> cross-env START_HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js
```

**Comment by Wilba6582** [comment]
Try turning off dark mode in Win10.

https://github.com/electron/electron/issues/19468

**Comment by f97** [comment]
> Try turning off dark mode in Win10.
> 
> [electron/electron#19468](https://github.com/electron/electron/issues/19468)

Tkanks... It work.. :)))

**Comment by dalexhd** [comment]
> Try turning off dark mode in Win10.
> 
> [electron/electron#19468](https://github.com/electron/electron/issues/19468)

Thanks a lot. IDK why doesn't work on dark mode...
