### ISSUE TITLE
Routes stop working when rearranged

### ISSUE THREAD

**Issue by jaykch** [electron-react-boilerplate/electron-react-boilerplate#2399]
Is there some weird cache going on? My routes stop working when I rearrange Routes.tsx
This works (even though Register and testing routes show home component for some reason.
) -

```
<Switch>
        <Route path={routes.NEW} component={NewPage}/>
        <Route path={routes.LOGIN} component={LoginPage}/>
        <Route path={routes.HOME} component={HomePage}/>
        <Route path={routes.REGISTER} component={NewPage}/>
        <Route path={routes.TESTING} component={NewPage}/>
</Switch>
```

This does not work

```
<Switch>
        <Route path={routes.HOME} component={HomePage}/>
        <Route path={routes.LOGIN} component={LoginPage}/>
        <Route path={routes.REGISTER} component={NewPage}/>
        <Route path={routes.TESTING} component={NewPage}/>
        <Route path={routes.NEW} component={NewPage}/>
</Switch>
```

removing switch fixes everything but then they are all on top of home component
I have tried 
```yarn cache clear```

**Comment by qtisan** [comment]
in trap too.

**Comment by jaykch** [comment]
Actually the issue is, in Routes.tsx they use react-router but in counter component and home component they use react-router-dom.

Using either will fix all routing issues -

I changed -

```
import { Switch, Route } from 'react-router';
```
To this -
```
import { Route, Switch } from "react-router-dom";
```

In apps/Routes.tsx

Fixed all routing issues.

**Comment by ZhangBohan** [comment]
the `exact` keyword works for me, change to `react-router-dom` still not working

**Comment by MSmithDev** [comment]
I'm also having the same issue even after the "react-router-dom" fix was added. Changing them all to exact path is working though.
