### ISSUE TITLE
Home Route should exact match to make adding new pages slightly less difficult

### ISSUE THREAD

**Issue by akoskm** [electron-react-boilerplate/electron-react-boilerplate#2402]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

As a rookie electron developer, I would expect that any new paths I throw into the router - following the already established principles, meaning, _basically_ copying Counter and renaming it - will work.

## Current Behavior

They don't. Paths are not exactly matched, any path starting with `/` and coming after `Home` will map to `Home`. Complete diff is in https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2388#issuecomment-596062525. So if you want to throw together a POC in a few minutes and overlook this tiny detail you'll spend some time looking for what you did wrong. 😅 I feel this adds some unnecessary complication and instead of developing something real fast I end up looking at react-router documentation.

## Possible Solution

Exact path matching could be turned on for `Home` or a comment could be added above `Home` warning about paths not being exactly matched.

**Comment by qtisan** [comment]
#2399

**Comment by jaykch** [comment]
Actually the issue is, in Routes.tsx they use react-router but in counter component and home component they use react-router-dom.

Using either will fix all routing issues -

I changed -

```
import { Switch, Route } from 'react-router';
```
To this -
```
import { Route, Switch } from "react-router-dom";
```

In apps/Routes.tsx

Fixed all routing issues.

**Comment by exogenesys** [comment]
I faced the problem as @akoskm and ended up spending a lot of time finding out where I went wrong. Even though `react-router-dom` was used in the `Routes.tsx` as suggested , the problem still occurred. The solution was to write:

```      
<Switch>
        <Route path={routes.COUNTER} component={CounterPage} />
        <Route path={routes.CALCULATOR} component={CalculatorPage} />
        <Route path={routes.HOME} component={HomePage} />
</Switch>
```

Instead of:


```     
<Switch>
        <Route path={routes.COUNTER} component={CounterPage} />
        <Route path={routes.HOME} component={HomePage} />
        <Route path={routes.CALCULATOR} component={CalculatorPage} />
</Switch>
```

Which is almost lucky to stumble onto. I do not know what's a better solution but a comment in the `Router.tsx` would have helped a lot. :)

**Comment by jaykch** [comment]
Just switch them up to exact path, what might be happening is your other components loading on top of this component
