### ISSUE TITLE
Webpack Dev Server doing everything twice

### ISSUE THREAD

**Issue by thomaslai** [electron-react-boilerplate/electron-react-boilerplate#2442]
Using freshly cloned copy of electron react boilerplate, I noticed in the logs that WDS logs seems to be called twice, for example:
![image](https://user-images.githubusercontent.com/542929/80128744-f43e0200-854a-11ea-8ddf-128ce583ed0e.png)

## Prerequisites

- [✓] Using yarn
- [✓] Using node 10.x (v12.16.1)
- [✓] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master) (commit hash 63cebabb467400c910acf51fa7a0b9285b7bff22)
- [?] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools) (I assume this is current since its freshly cloned, this url seems to be broken)
- [X] Link to stacktrace in a Gist (for bugs)
- [X] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400) (not an installation issue)

## Expected Behavior

WDS should just do stuff like hot reloading and recompiling only once

## Current Behavior

Webpack seems to be called twice, or have 2 instances or something, and seems to be recompiling every change twice. (see picture at top)

## Possible Solution

I don't really understand WDS but would like to learn more

## Steps to Reproduce (for bugs)

1) Git clone electron react boilerplate
2) yarn
3) yarn dev
4) Look at dev console

1.

2.

3.

4.

## Context

Not quite sure, but it seems like unintended behavior.

Yes but I did a fresh clone just to confirm that this wasn't caused by our code.

## Your Environment

- Node version : v12.16.1
- Version or Branch used : electron react boilerplate v1.1.0, git commit hash 63cebabb467400c910acf51fa7a0b9285b7bff22
- Operating System and version : Microsoft Windows 10 Pro Version 10.0.18363 Build 18363
- Link to your project : Not available

**Comment by steveetm** [comment]
Hey, check this PR please:
https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2443

**Comment by thomaslai** [comment]
Can confirm that your changes do indeed remove that extra copy of webpack logs. Do you know why it was added in the first place? Will this fix be breaking anything?

**Comment by steveetm** [comment]
I don't think it should break anything, `devServer` configured as inline, so it should inject the necessary modules for HMR. Also, this method is mainly used when you instantiate webpack-dev-server via nodejs api (and legacy webpack maybe?) If you find anything broken please tell me.

However as I stated on PR, I closed it for now as there is other issue with HMR, I'll fix that too and resend that when everything is cleaned up.

**Comment by ratoi-crysty** [comment]
I'm not sure if this is related, but if you just clone the boilerplate, delete all the example code (counter) and in the `AppContainer` you just add a `div` with a text (this is to make the build as fast as possible). 
Now, whenever you update the code, the app reload is done before the changes are applied, therefore ending with the previous version of the app.
 You will need to do a manual refresh, to actually get the changes.

PS. I added this comment here as I guessed this happens because of the 2 builds, after the first build is completed, it probably triggers the reload before the actual build with the changes completes, but I can be mistaken.

**Comment by steveetm** [comment]
I totally forgot about this one, the proposed fix can be found in #2443 , I will try to review and rebase it soon.

**Comment by amilajack** [comment]
Thanks @steveetm !

**Comment by amilajack** [comment]
This has been fixed in the most recent version of the boilerplate

**Comment by SergiiMarkin** [comment]
Hi @amilajack 
This issue is still persisted
![image](https://user-images.githubusercontent.com/85687049/157843364-4749670e-6f79-4afd-bd5a-14311a23bf0a.png)
I run the fresh boilerplate and opened inspect window.
As you see the above image, rendered twice time.

**Comment by welljsjs** [comment]
We're experiencing the same issue and it's causing us some headache. We're on the latest version 4.6.0. 

Can this please be investigated? This is irritating especially when we're establishing a web socket connection that is now established twice. 

Thank you.

@steveetm

**Comment by steveetm** [comment]
@welljsjs Sorry, I totally forgot about that, tbh my previous work involved with electron finished and I didn't have much time to contribute there but I'll check as my time permits if I can still repro the same issue.

**Comment by varwasabi** [comment]
I believe this has something to do with the entries array in `webpack.config.renderer.dev.ts`. Just having the file path eliminates the doubling up.
